spring:
  datasource:
    url: jdbc:mariadb://${DB}:3306/boot_db?useUnicode=true&charaterEncoding =utf-8&useSSL=false&serverTimezone=UTC
    username: boot
    password: boot
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

DB: 127.0.0.1